* Revert https://reviews.llvm.org/D95727 as it is causing some issues like:   - /usr/bin/ld: ./build-llvm/lib/ExecutionEngine/Interpreter/./llvm/lib/ExecutionEngine/Interpreter/ExternalFunctions.cpp:135: undefined reference to `ffi_type_pointer'   -  Host compiler must support std::atomic!